/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LibroDAO;
import java.awt.Font;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import modelo.Libro;

/**
 *
 * @author Veymar Montaño Colqu
 */
public class BuscadorLibros extends javax.swing.JDialog {
    private LibroDAO controladorLibro;
    private String[] titulosTabla;
    
    private String filtroDeBusquedaActual;//Nos dice que filtro De Busqueda esta activado actualmente
    
    private DefaultTableModel tableModel;
    private Font fuenteOriginalLabel;//fuente auxiliar para cambiar los controles atras y adelante
    private int anchoOriginalLabel;//ancho auxiliar para cambiar los controles atras y adelante
    
    private final String POR_TITULO="Ingrese título del libro";
    private final String POR_AUTOR="Ingrese autor del libro";
    private final String POR_TEMA="Ingrese tema del libro";
    
    private ArrayList<Libro>registroLibros;
    private String filtroActual;
    private int filaSeleccionada;
    private boolean seSeleccionoUnLibro;
    /**
     * Creates new form BuscadorLibros
     * @param parent
     * @param modal
     */
    public BuscadorLibros(JDialog parent, boolean modal) {
        super(parent, modal);
        
        titulosTabla = new String[]{"ID","TITULO","EDICION","TEMA","AUTOR"};                       
        
        controladorLibro = new LibroDAO();
        
        initComponents();
        tableModel = (DefaultTableModel)tableRegistroLibros.getModel();
        
        this.setLocationRelativeTo(null);
        
                        
        btnRadioTitulo.setSelected(true);
        txtBuscar.setText(POR_TITULO);

        filtroActual = "Por Titulo";//Nos dice que actualmente esta seleccionado titulo
                
        
        establecerDatosTabla(btnRadioTitulo);
        
        tableRegistroLibros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableRegistroLibros.getSelectionModel().setSelectionInterval(0, 0);
        
        seSeleccionoUnLibro = false;
        
        añadirEventoALaTabla();
    }
    
    private void añadirEventoALaTabla(){
        tableRegistroLibros.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                filaSeleccionada =  tableRegistroLibros.getSelectedRow();
            }

          });
    }
    
    public Libro getLibroBuscado(){
        Libro respuesta = null;
        
        if(seSeleccionoUnLibro)
            respuesta = registroLibros.get(filaSeleccionada);
        return respuesta;
    }
    
    private void establecerDatosTabla(JRadioButton radiobuttonOpcion){
        if(comboBoxSeleccionLibros.getSelectedItem().equals("Libreria")){
            registroLibros = controladorLibro.getReportePorFiltro(radiobuttonOpcion.getText());
        }
        else{
            String condicion = "where cantidad != 0 and estado = 0";
            registroLibros = controladorLibro.getReportePorFiltro(
                    radiobuttonOpcion.getText(), condicion);
        }

        filaSeleccionada = 0;
        
        Object[][] arregloDatosLibro = conseguirDatosLibro(registroLibros);
        tableModel.setDataVector(arregloDatosLibro, titulosTabla);        
    }
    
    private Object[][] conseguirDatosLibro(ArrayList<Libro> registroLibros){
        Object[][] respuesta = new Object[registroLibros.size()][];
        
        for (int i = 0; i < respuesta.length; i++) {
            respuesta[i] = convertirLibroAArreglo(registroLibros.get(i));
        }
        
        return respuesta;
    }
    
    private Object[] convertirLibroAArreglo(Libro libro){
        Object [] respuesta = new Object[5];
        
        respuesta[0] = libro.getIdLibro();
        respuesta[1] = libro.getNombreLibro();
        respuesta[2] = libro.getEdicion();
        respuesta[3] = libro.getGenero();
        respuesta[4] = libro.getAutorLibro();
        
        return respuesta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_filtro = new javax.swing.ButtonGroup();
        panelContenedorPrincipal = new javax.swing.JPanel();
        laberSeleccionar = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        panelControlesDeFiltros = new javax.swing.JPanel();
        labelTituloBuscar = new javax.swing.JLabel();
        btnRadioTitulo = new javax.swing.JRadioButton();
        btnRadioAutor = new javax.swing.JRadioButton();
        btnRadioTema = new javax.swing.JRadioButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPanePanelTabla = new javax.swing.JScrollPane();
        tableRegistroLibros = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelTituloBuscar1 = new javax.swing.JLabel();
        comboBoxSeleccionLibros = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Libro..");

        panelContenedorPrincipal.setBackground(new java.awt.Color(5, 5, 28));

        laberSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laberSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        laberSeleccionar.setText("Seleccione el libro que busca:");

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        panelControlesDeFiltros.setBackground(new java.awt.Color(5, 5, 28));
        panelControlesDeFiltros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        labelTituloBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTituloBuscar.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloBuscar.setText("Buscar por:");

        btnGroup_filtro.add(btnRadioTitulo);
        btnRadioTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRadioTitulo.setForeground(new java.awt.Color(255, 255, 255));
        btnRadioTitulo.setText("Por Titulo");
        btnRadioTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioTituloMouseClicked(evt);
            }
        });

        btnGroup_filtro.add(btnRadioAutor);
        btnRadioAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRadioAutor.setForeground(new java.awt.Color(255, 255, 255));
        btnRadioAutor.setText("Por Autor");
        btnRadioAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioAutorMouseClicked(evt);
            }
        });

        btnGroup_filtro.add(btnRadioTema);
        btnRadioTema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRadioTema.setForeground(new java.awt.Color(255, 255, 255));
        btnRadioTema.setText("Por Tema");
        btnRadioTema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioTemaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelControlesDeFiltrosLayout = new javax.swing.GroupLayout(panelControlesDeFiltros);
        panelControlesDeFiltros.setLayout(panelControlesDeFiltrosLayout);
        panelControlesDeFiltrosLayout.setHorizontalGroup(
            panelControlesDeFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesDeFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlesDeFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlesDeFiltrosLayout.createSequentialGroup()
                        .addComponent(btnRadioTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRadioTema)
                        .addGap(131, 131, 131)
                        .addComponent(btnRadioAutor)
                        .addGap(14, 14, 14))
                    .addGroup(panelControlesDeFiltrosLayout.createSequentialGroup()
                        .addComponent(labelTituloBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelControlesDeFiltrosLayout.setVerticalGroup(
            panelControlesDeFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesDeFiltrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTituloBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelControlesDeFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioTitulo)
                    .addComponent(btnRadioTema)
                    .addComponent(btnRadioAutor))
                .addContainerGap())
        );

        panelTabla.setLayout(null);

        tableRegistroLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "EDICION", "TEMA", "AUTOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRegistroLibros.getTableHeader().setReorderingAllowed(false);
        tableRegistroLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRegistroLibrosMouseClicked(evt);
            }
        });
        jScrollPanePanelTabla.setViewportView(tableRegistroLibros);

        panelTabla.add(jScrollPanePanelTabla);
        jScrollPanePanelTabla.setBounds(10, 11, 920, 186);

        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(5, 5, 28));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        labelTituloBuscar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTituloBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloBuscar1.setText("Buscar en:");

        comboBoxSeleccionLibros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxSeleccionLibros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libreria", "Dados de baja" }));
        comboBoxSeleccionLibros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxSeleccionLibrosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTituloBuscar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(comboBoxSeleccionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloBuscar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSeleccionLibros)
                .addGap(8, 8, 8))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR LIBRO");

        javax.swing.GroupLayout panelContenedorPrincipalLayout = new javax.swing.GroupLayout(panelContenedorPrincipal);
        panelContenedorPrincipal.setLayout(panelContenedorPrincipalLayout);
        panelContenedorPrincipalLayout.setHorizontalGroup(
            panelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelControlesDeFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelContenedorPrincipalLayout.createSequentialGroup()
                        .addGroup(panelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laberSeleccionar)
                            .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402))
        );
        panelContenedorPrincipalLayout.setVerticalGroup(
            panelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelControlesDeFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laberSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRadioTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioTituloMouseClicked
        if(!filtroActual.equals("Por Titulo")){
            iniciarDatosTabla("Por Titulo", POR_TITULO, btnRadioTitulo);
        }
    }//GEN-LAST:event_btnRadioTituloMouseClicked

    private void btnRadioAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioAutorMouseClicked
        if(!filtroActual.equals("Por Autor")){
            iniciarDatosTabla("Por Autor", POR_AUTOR, btnRadioAutor);
        }
    }//GEN-LAST:event_btnRadioAutorMouseClicked

    private void btnRadioTemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioTemaMouseClicked
        if(!filtroActual.equals("Por Tema")){
            iniciarDatosTabla("Por Tema", POR_TEMA, btnRadioTema);
        }
    }//GEN-LAST:event_btnRadioTemaMouseClicked
    
    private void iniciarDatosTabla(String filtro, String txt_descripcion, 
            javax.swing.JRadioButton radioButton){
        filtroActual = filtro;//parametro por el cual buscara
        controladorLibro.reiniciarParametroNoEncontrado();//
        txtBuscar.setText(txt_descripcion);
        establecerDatosTabla(radioButton);
        deslizarTablaHastaSeleccion(0);//muestra la fila seleccionada de la tabla
    }
    
    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarFocusGained

    private void tableRegistroLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRegistroLibrosMouseClicked
        int fila = tableRegistroLibros.rowAtPoint(evt.getPoint());
        if(fila>=0){

        }
    }//GEN-LAST:event_tableRegistroLibrosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        filaSeleccionada = controladorLibro.encontrarPrimeraCoincidencia(
                txtBuscar.getText(),filtroActual);
        if(filaSeleccionada != -1){
            deslizarTablaHastaSeleccion(filaSeleccionada);
        }            
        else
        if(txtBuscar.getText().equals("")){
            filaSeleccionada = 0;
            deslizarTablaHastaSeleccion(filaSeleccionada);
        }                
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        if(registroLibros.get(filaSeleccionada).getStockDisponible()>0){
            seSeleccionoUnLibro = true;
            dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "EL STOCK DE ESTE LIBRO ESTA AGOTADO,"
                    + "SELECCIONE OTRO POR FAVOR..");
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void comboBoxSeleccionLibrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxSeleccionLibrosItemStateChanged
        System.out.println("se ejecuta........");
        iniciarDatosTabla("Por Titulo", POR_TITULO, btnRadioTitulo);
        btnRadioTitulo.setSelected(true);
    }//GEN-LAST:event_comboBoxSeleccionLibrosItemStateChanged
    
    
    private void deslizarTablaHastaSeleccion(int filaSeleccionada){
        tableRegistroLibros.getSelectionModel().setSelectionInterval(
                filaSeleccionada, filaSeleccionada);
        Rectangle rect = tableRegistroLibros.getCellRect(filaSeleccionada, 0, true);
        tableRegistroLibros.scrollRectToVisible(rect);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscadorLibros dialog = new BuscadorLibros(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                System.out.println(dialog.getLibroBuscado().getNombreLibro());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup btnGroup_filtro;
    private javax.swing.JRadioButton btnRadioAutor;
    private javax.swing.JRadioButton btnRadioTema;
    private javax.swing.JRadioButton btnRadioTitulo;
    private javax.swing.JComboBox comboBoxSeleccionLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPanePanelTabla;
    private javax.swing.JLabel labelTituloBuscar;
    private javax.swing.JLabel labelTituloBuscar1;
    private javax.swing.JLabel laberSeleccionar;
    private javax.swing.JPanel panelContenedorPrincipal;
    private javax.swing.JPanel panelControlesDeFiltros;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tableRegistroLibros;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
