/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.Libro;

/**
 *
 * @author Juan Pablo
 */
public class EdicionCantidad extends javax.swing.JDialog {

    RegistroVentas ventana;
    ArrayList<Libro> ventas;
    JTable tabla;
    JTextField costoTotal;
    int fila;
    
    public EdicionCantidad(JDialog parent, boolean modal, 
                    RegistroVentas ventana, int fila) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventana = ventana;
        this.fila = fila;
        tabla = ventana.getVentaTabla();
        ventas = ventana.getListaPorVender();
        costoTotal = ventana.getCostoTotal();
        txtCantidad.setText(String.valueOf(ventana.getVentaTabla().getValueAt(fila, 0)));
        avisoCantidadLB.setText(null);
    }

    public void cambiarCantidadLibro(int fila){
        for(Libro x : ventas){
            if(((String)tabla.getValueAt(fila, 1)).equals(x.getNombreLibro())
            && ((String)tabla.getValueAt(fila, 2)).equals(x.getAutorLibro())
            ){
                if(txtCantidad.getText().trim().length() == 0){
                    avisoCantidadLB.setText("Agregue un valor");
                }else{
                    
                    Integer valorActual = Integer.parseInt(txtCantidad.getText());
                    int valor = x.getStockDisponible();
                    
                    if(txtCantidad.getText().equals("0") || valorActual == 0){
                        avisoCantidadLB.setText("Debe venderse por lo menos 1 libro");
                    }else{
                        
                        if(valorActual <= valor){
                            Double precio = Double.parseDouble((String)tabla.getValueAt(fila, 3));
                            tabla.setValueAt(String.valueOf(valorActual), fila, 0);
                            tabla.setValueAt(valorActual*precio, fila, 4);
                            ventana.sumar();
                            dispose();
                        }else{
                            avisoCantidadLB.setText("El cantidad disponible de este libro es : " + valor);
                        }
                        
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        aceptarCantidadJB = new javax.swing.JButton();
        avisoCantidadLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 5, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregue la cantidad de este libro a vender: ");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        aceptarCantidadJB.setText("Aceptar");
        aceptarCantidadJB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarCantidadJBMouseClicked(evt);
            }
        });

        avisoCantidadLB.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        avisoCantidadLB.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(avisoCantidadLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(aceptarCantidadJB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(avisoCantidadLB, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(aceptarCantidadJB)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarCantidadJBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarCantidadJBMouseClicked
        cambiarCantidadLibro(fila);
    }//GEN-LAST:event_aceptarCantidadJBMouseClicked

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        if (!Character.isDigit(evt.getKeyChar())
                || txtCantidad.getText().length()>7) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCantidadJB;
    private javax.swing.JLabel avisoCantidadLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
