package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
 

public class Grafico extends javax.swing.JPanel {

    
    public Grafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloGraficos = new javax.swing.JLabel();
        panelBase = new javax.swing.JPanel();
        btnElegirGrafico = new javax.swing.JButton();
        labelMasVendidos = new javax.swing.JLabel();
        spinnerCantidadMasVendidos = new javax.swing.JSpinner();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(5, 5, 28));
        setPreferredSize(new java.awt.Dimension(792, 556));
        setLayout(null);

        lblTituloGraficos.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblTituloGraficos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloGraficos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloGraficos.setText("TITULO DE LOS GRAFICOS");
        lblTituloGraficos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblTituloGraficos);
        lblTituloGraficos.setBounds(93, 0, 578, 45);

        panelBase.setBackground(new java.awt.Color(5, 5, 28));
        panelBase.setPreferredSize(new java.awt.Dimension(300, 422));

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        add(panelBase);
        panelBase.setBounds(10, 100, 770, 445);

        btnElegirGrafico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnElegirGrafico.setText("Elegir Gráfico");
        add(btnElegirGrafico);
        btnElegirGrafico.setBounds(670, 60, 110, 30);

        labelMasVendidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMasVendidos.setForeground(new java.awt.Color(255, 255, 255));
        labelMasVendidos.setText("Cantidad de libros más vendidos:");
        add(labelMasVendidos);
        labelMasVendidos.setBounds(30, 60, 230, 20);

        spinnerCantidadMasVendidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinnerCantidadMasVendidos.setModel(new javax.swing.SpinnerNumberModel(2, 1, 7, 1));
        spinnerCantidadMasVendidos.setMinimumSize(new java.awt.Dimension(45, 22));
        spinnerCantidadMasVendidos.setPreferredSize(new java.awt.Dimension(45, 22));
        add(spinnerCantidadMasVendidos);
        spinnerCantidadMasVendidos.setBounds(270, 60, 50, 30);

        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        add(btnActualizar);
        btnActualizar.setBounds(550, 60, 109, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnElegirGrafico;
    private javax.swing.JLabel labelMasVendidos;
    private javax.swing.JLabel lblTituloGraficos;
    private javax.swing.JPanel panelBase;
    private javax.swing.JSpinner spinnerCantidadMasVendidos;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getPanelBase()
    {
        return panelBase;
    }
    
    public JButton getBtnElegirGrafico(){
        return btnElegirGrafico;
    }
    
    public JButton getBtnActualizar()
    {
        return btnActualizar;
    }
 
    public JLabel getLabelMasVendidos(){
        return labelMasVendidos;
    }
    
    public JSpinner getSpinnerCantidadMasVendidos(){
        return spinnerCantidadMasVendidos;
    }
    
    public JLabel getlblTituloGraficos(){
        return lblTituloGraficos;
    }
}
