 
package vista;

import controlador.ControladorIngresar;
import java.awt.Dimension;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

 
public class Inicio extends javax.swing.JFrame {

    private PanelInicio panelInicio;
    private ControladorIngresar ingreso;
    
    public Inicio() {
        initComponents();
        pnlBaseInicio.setSize(new Dimension(965, 655));
        this.setLocationRelativeTo(null);
        
        panelInicio = new PanelInicio();        
        pnlBaseInicio.add(panelInicio);
        pnlBaseInicio.updateUI();
        menuInicio.setVisible(false);
       
        ControladorIngresar ingreso = new ControladorIngresar(this, panelInicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBaseInicio = new javax.swing.JPanel();
        menuBarInicio = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBaseInicio.setBackground(new java.awt.Color(5, 5, 28));
        pnlBaseInicio.setPreferredSize(new java.awt.Dimension(979, 605));

        javax.swing.GroupLayout pnlBaseInicioLayout = new javax.swing.GroupLayout(pnlBaseInicio);
        pnlBaseInicio.setLayout(pnlBaseInicioLayout);
        pnlBaseInicioLayout.setHorizontalGroup(
            pnlBaseInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlBaseInicioLayout.setVerticalGroup(
            pnlBaseInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        menuBarInicio.setBackground(new java.awt.Color(5, 5, 28));
        menuBarInicio.setBorder(null);
        menuBarInicio.setPreferredSize(new java.awt.Dimension(58, 35));

        menuInicio.setBackground(new java.awt.Color(5, 5, 28));
        menuInicio.setForeground(new java.awt.Color(5, 5, 28));
        menuInicio.setText("INICIO");
        menuInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });

        itemSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSalirMouseClicked(evt);
            }
        });
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuInicio.add(itemSalir);

        menuBarInicio.add(menuInicio);

        setJMenuBar(menuBarInicio);
        menuBarInicio.getAccessibleContext().setAccessibleDescription("");
        menuBarInicio.setBackground(new java.awt.Color(51,51,55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBaseInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBaseInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        
    }//GEN-LAST:event_menuInicioMouseClicked

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSalirMouseClicked

    }//GEN-LAST:event_itemSalirMouseClicked

    public JMenuItem getItemSalir() {
        return itemSalir;
    }

    public JMenu getMenuInicio() {
        return menuInicio;
    }

    public JPanel getPnlBaseInicio() {
        return pnlBaseInicio;
    }

    public JMenuBar getMenuBarInicio() {
        return menuBarInicio;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar menuBarInicio;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JPanel pnlBaseInicio;
    // End of variables declaration//GEN-END:variables
}
