/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Veymar Montaño Colqu
 */
public class RegistroCompras2 extends JPanel {
    private JScrollPane scrollPanel;
    private JPanel panelTabla;
    private JScrollPane scrollTabla;
    private JTable tablaDesplegable;
    private final String[] titulosTabla = {"TITULO","AUTOR","GENERO","EDICION",
                  "CATIDAD","COMPRA","VENTA","MINIMO"};
    
    private JTextFieldP txtTitulo;
    private JTextFieldP txtAutor;
    private JTextFieldP txtGenero;
    private JTextFieldP txtEdicion;
    private JTextFieldP txtCantidad;
    private JTextFieldP txtPrecioCompra;
    private JTextFieldP txtPrecioVenta;
    private JTextFieldP txtCantidadMinima;
    
    private JButton btnLimpiar;
    private JButton btnAgregar;

    /**
     * Creates new form RegistroCompras
     */
    public RegistroCompras2() {
        initComponents();
        initOtherComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelTituloBuscar = new javax.swing.JLabel();
        comboBoxBuscarEn = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(5, 5, 28));
        setPreferredSize(new java.awt.Dimension(798, 556));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE COMPRAS Y STOCK");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1);
        jLabel1.setBounds(252, 11, 372, 59);

        labelTituloBuscar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelTituloBuscar.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloBuscar.setText("Buscar :");
        add(labelTituloBuscar);
        labelTituloBuscar.setBounds(46, 74, 82, 25);

        comboBoxBuscarEn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "lista de libros", "contro de stock", "libros dados de baja" }));
        add(comboBoxBuscarEn);
        comboBoxBuscarEn.setBounds(47, 105, 170, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void initOtherComponents() {
        txtTitulo = new JTextFieldP();
        txtAutor = new JTextFieldP();
        txtGenero = new JTextFieldP();
        txtEdicion = new JTextFieldP();
        txtCantidad = new JTextFieldP();
        txtPrecioCompra = new JTextFieldP();
        txtPrecioVenta = new JTextFieldP();
        txtCantidadMinima = new JTextFieldP();
        

        panelTabla = new JPanel();
        scrollPanel = new JScrollPane();
        tablaDesplegable = new JTable();
        scrollTabla = new JScrollPane();
        
        panelTabla.setPreferredSize(new Dimension(900, 275));
        panelTabla.setLayout(null);
        
        DefaultTableModel tableModel = (DefaultTableModel)tablaDesplegable.getModel();
        tableModel.setDataVector(null, titulosTabla);
        
        tableModel = (DefaultTableModel)tablaDesplegable.getModel();
        tableModel.setDataVector(null, titulosTabla);
        
        TableColumnModel columnModel = tablaDesplegable.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(200);
        columnModel.getColumn(1).setPreferredWidth(200);
        columnModel.getColumn(2).setPreferredWidth(130);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(100);
        columnModel.getColumn(7).setPreferredWidth(100);
        
        scrollTabla.setViewportView(tablaDesplegable);
        panelTabla.add(scrollTabla);
        scrollTabla.setBounds(0, 0, 900, 275);
        
        scrollPanel.setViewportView(panelTabla);
        add(scrollPanel);
        scrollPanel.setBounds(47, 166, 748, 300);
        scrollPanel.setVisible(false);

        
        btnLimpiar = new JButton("limpiar");
        btnAgregar = new JButton("agregar");

        txtTitulo.setPlaceholder("titulo");
        add(txtTitulo);
        txtTitulo.setBounds(47, 140, 190, 30);

        txtAutor.setPlaceholder("autor");
        add(txtAutor);
        txtAutor.setBounds(233, 140, 190, 30);

        txtGenero.setPlaceholder("genero");
        add(txtGenero);
        txtGenero.setBounds(419, 140, 190, 30);

        txtEdicion.setPlaceholder("edición");
        add(txtEdicion);
        txtEdicion.setBounds(605, 140, 190, 30);

        txtCantidad.setPlaceholder("cantidad");
        add(txtCantidad);
        txtCantidad.setBounds(47, 170, 125, 30);

        txtPrecioCompra.setPlaceholder("precio de compra");
        add(txtPrecioCompra);
        txtPrecioCompra.setBounds(168, 170, 125, 30);

        txtPrecioVenta.setPlaceholder("precio de venta");
        add(txtPrecioVenta);
        txtPrecioVenta.setBounds(289, 170, 125, 30);

        txtCantidadMinima.setPlaceholder("cantidad mínima");
        add(txtCantidadMinima);
        txtCantidadMinima.setBounds(410, 170, 125, 30);
        
        add(btnLimpiar);
        btnLimpiar.setBounds(600, 170, 90, 30);
        
        add(btnAgregar);
        btnAgregar.setBounds(700, 170, 90, 30);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxBuscarEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelTituloBuscar;
    // End of variables declaration//GEN-END:variables

    public JTextFieldP getTxtTitulo() {
        return txtTitulo;
    }

    public JTextFieldP getTxtAutor() {
        return txtAutor;
    }

    public JTextFieldP getTxtGenero() {
        return txtGenero;
    }

    public JTextFieldP getTxtEdicion() {
        return txtEdicion;
    }

    public JTextFieldP getTxtCantidad() {
        return txtCantidad;
    }

    public JTextFieldP getTxtPrecioCompra() {
        return txtPrecioCompra;
    }

    public JTextFieldP getTxtPrecioVenta() {
        return txtPrecioVenta;
    }

    public JTextFieldP getTxtCantidadMinima() {
        return txtCantidadMinima;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JTable getTablaDesplegable() {
        return tablaDesplegable;
    }

    public JScrollPane getScrollPanel() {
        return scrollPanel;
    }

    public JComboBox getComboBoxBuscarEn() {
        return comboBoxBuscarEn;
    }


}
