/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.LibroDAO;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelo.Libro;

/**
 *
 * @author pcs
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistro
     */
    private LibroDAO controladorLibro;
    private DefaultTableModel tableModel;
    private String[] titulosTabla;
    private ArrayList<Libro>registroLibros;
    private int filaSeleccionada;
    private boolean libroElegido;
    
    public VentanaRegistro() {
        initComponents();
        controladorLibro = new LibroDAO();
        this.setLocationRelativeTo(null);
        
        tableModel = (DefaultTableModel)tablaLibros.getModel();
        titulosTabla = new String[]{"ID", "TITULO","AUTOR", "EDICION", "CANTIDAD", "STOCK"};
        
        establecerDatosTabla();
        
        tablaLibros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaLibros.getSelectionModel().setSelectionInterval(0, 0);
        
        libroElegido = false;
        
        añadirEventoALaTabla(); 
        
    }
    
    private void añadirEventoALaTabla(){
        tablaLibros.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                filaSeleccionada =  tablaLibros.getSelectedRow();
            }

          });
    }
    
    public Libro getLibroAEditar(){
        Libro respuesta = null;
        
        if(libroElegido)
            respuesta = registroLibros.get(filaSeleccionada);
        return respuesta;
    }
    
    public void establecerDatosTabla(){
        registroLibros = controladorLibro.getReportePorFiltro("Por Titulo");
        filaSeleccionada = 0;
        Object[][] arregloDatosLibro = conseguirDatosLibro(registroLibros);
        tableModel.setDataVector(arregloDatosLibro, titulosTabla);        
    }
    
    private Object[][] conseguirDatosLibro(ArrayList<Libro> registroLibros){
        Object[][] respuesta = new Object[registroLibros.size()][];
        
        for (int i = 0; i < respuesta.length; i++) {
            respuesta[i] = convertirLibroAArreglo(registroLibros.get(i));
        }
        
        return respuesta;
    }
    
    private Object[] convertirLibroAArreglo(Libro libro){
        Object [] respuesta = new Object[6];
        
        respuesta[0] = libro.getIdLibro();
        respuesta[1] = libro.getNombreLibro();
        respuesta[2] = libro.getAutorLibro();
        respuesta[3] = libro.getEdicion();
        respuesta[4] = libro.getStockDisponible();
        respuesta[5] = libro.getStockMinimo();
        
        return respuesta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnEditarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 5, 28));

        jButton1.setText("Comprar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnEditarLibro.setText("Editar Libro");
        btnEditarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarLibroMouseClicked(evt);
            }
        });
        btnEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLibroActionPerformed(evt);
            }
        });

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Autor", "Edición", "Cantidad", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaLibros);
        if (tablaLibros.getColumnModel().getColumnCount() > 0) {
            tablaLibros.getColumnModel().getColumn(0).setResizable(false);
            tablaLibros.getColumnModel().getColumn(1).setResizable(false);
            tablaLibros.getColumnModel().getColumn(2).setResizable(false);
            tablaLibros.getColumnModel().getColumn(3).setResizable(false);
            tablaLibros.getColumnModel().getColumn(4).setResizable(false);
            tablaLibros.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditarLibro)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEditarLibro))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        boolean tengoLibro=true;
        Libro libro=new Libro(1,"La Odisea","Homero", "Novela", "Primera edicion" ,10, 20,30);
        FormularioLibro f= new FormularioLibro(this, true, tengoLibro, libro);
        f.setVisible(true);
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnEditarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarLibroMouseClicked
        int countRow = getVentanaLibros().getRowCount();
        if(countRow > 0)
        {
            int row = getVentanaLibros().getSelectedRow();
            if(row >= 0)
            {
                libroElegido = true;
                editarLibro(row);
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Seleccione una fila para editar el libro");
            }
        }
    }//GEN-LAST:event_btnEditarLibroMouseClicked

    private void editarLibro(int row){
        Libro libroAEditar = getLibroAEditar();
        EdicionLibro edicionLibro = new EdicionLibro(new javax.swing.JDialog(), true, this, libroAEditar);
                edicionLibro.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                        Window buscador = e.getWindow();
                        if(buscador instanceof JDialog)
                            ((JDialog)buscador).dispose();
                    }
                });
        edicionLibro.setVisible(true);
    }
    
    
    private void btnEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarLibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
    
    private JTable getVentanaLibros(){
        return tablaLibros;
    }

}
